apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169832346
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169832346
    app.kubernetes.io/part-of: test-app-169832346
  name: java-quarkus-169832346
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169832346
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169832346
    spec:
      containers:
      - image: quay.io/hacdev/j2gbrphk-tenant/test-app-169832346/java-quarkus-169832346@sha256:22b91dc6a67f1a8dd324ad4148679122a68c3c2432a0c8e8f224e5a6f088fff2
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
